name: Update Docker Hub Description

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v6
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: skyjia/soco-cli
          readme-filepath: ./README.md
